import type { Mesh, MeshStandardMaterial } from "three";
import type { GLTF } from "three-stdlib";
import { OrbitControls, useGLTF } from "@react-three/drei";
import { ReactElement, useRef } from "react";
import { useFrame } from "@react-three/fiber";

/** gltfjsx generated type */
type GLTFResult = GLTF & {
  nodes: {
    Object_4: Mesh;
    Object_5: Mesh;
    Object_6: Mesh;
    Object_7: Mesh;
    Object_8: Mesh;
    Object_9: Mesh;
    Object_10: Mesh;
  };
  materials: {
    NovelKeys: MeshStandardMaterial;
    Lime: MeshStandardMaterial;
    Grape: MeshStandardMaterial;
    Blueberry: MeshStandardMaterial;
    Lemon: MeshStandardMaterial;
    Strawberry: MeshStandardMaterial;
    /**
     * #E3E3E3 - taken for a background color
     * @see https://www.color-name.com/hex/e3e3e3
     */
    Material: MeshStandardMaterial;
  };
};

/**
 * A blank keyboard model without any positioning or rotation that is generated by gltfjsx
 * @author Joshua Sleepy
 * @see {@link https://sketchfab.com/3d-models/lowpoly-65-mechanical-keyboard-0cdd429eb08549ac954352169de5c8f8 Sketchfab original}
 * @license CC-BY-4.0
 * @param props Element props provided straight to the group
 * @returns {ReactElement} Group of meshes
 */
export const Model = (props: JSX.IntrinsicElements["group"]): ReactElement => {
  const { nodes, materials } = useGLTF(
    "/keyboard.glb"
  ) as unknown as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.NovelKeys} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Lime} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Grape} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.Blueberry} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Lemon} />
      <mesh
        geometry={nodes.Object_9.geometry}
        material={materials.Strawberry}
      />
      <mesh geometry={nodes.Object_10.geometry} material={materials.Material} />
    </group>
  );
}

/**
 * A keyboard model with orbit controls and auto rotation
 * @see {@link https://docs.pmnd.rs/react-three-fiber/api/canvas Canvas API}
 * @returns {ReactElement} Orbit controls and keyboard model that have to be wrapped in canvas
 */
export const Keyboard = (): ReactElement => {
  // Model mesh ref
  const meshRef: any = useRef();

  // Orbit controls ref
  const orbitRef: any = useRef();

  // Make a keyboard rotate left & right depending on the angle of the camera
  useFrame(() => {
    const azimuthalAngle = orbitRef.current.getAzimuthalAngle();
    if (azimuthalAngle > .5) {
      orbitRef.current.autoRotateSpeed = 1;
    } else if (azimuthalAngle < -.5) {
      orbitRef.current.autoRotateSpeed = -1;
    }
  });

  return (
    <>
      <ambientLight
        intensity={0.5} // Light from all directions
      />
      <directionalLight
        position={[0, 5, 0]} // Light from the above
      />
      <mesh ref={meshRef} scale={15} rotation={[Math.PI / 4, Math.PI / 12, 0]}>
        <Model />
      </mesh>
      <OrbitControls
        ref={orbitRef}
        minPolarAngle={Math.PI / 2} // Don't allow the camera to look down
        maxPolarAngle={0} // Don't allow the camera to look up
        enableZoom={false} // Don't allow the camera to zoom
        enablePan={false} // Don't allow the camera to pan
        autoRotate
        autoRotateSpeed={1}
      />
    </>
  );
}

// Preload the model
useGLTF.preload("/keyboard.glb");